[package]
name = "europa-rpc"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"

sc-client-api = "3.0.0"
sc-rpc = "3.0.0"

sp-api = "3.0.0"
sp-runtime = "3.0.0"
sp-transaction-pool = "3.0.0"
sc-keystore = "3.0.0"
sp-blockchain = "3.0.0"
sc-rpc-api = "0.9.0"
sp-block-builder = "3.0.0"
sp-consensus = "0.9.0"
sc-consensus-epochs = "0.9.0"

substrate-frame-rpc-system = "3.0.0"
pallet-transaction-payment-rpc = "3.0.0"

# vendor
pallet-contracts-rpc = "3.0.0"

europa-runtime = { path = "../runtime" }

