[package]
name = "europa-cli"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
serde_json = "1.0"

sp-consensus = "0.9.0"
sp-inherents = "3.0.0"
sp-timestamp = "3.0.0"
sp-core = "3.0.0"
sp-runtime = "3.0.0"

sc-cli = "0.9.0"
sc-transaction-pool = "3.0.0"
sc-consensus = "0.9.0"
sc-consensus-manual-seal = "0.9.0"
sc-basic-authorship = "0.9.0"

ec-service = { path = "../../../client/service" }
ec-cli = { path = "../../../client/cli" }

# vendor
pallet-contracts = { version = "3.0.0", path = "../../../vendor/substrate/frame/contracts" }

europa-runtime = { path = "../runtime" }
europa-executor = { path = "../executor" }
europa-rpc = { path = "../rpc" }

[build-dependencies]
substrate-build-script-utils = "3.0.0"
